// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-fvmCsw-UyKSCATxbpGho21-Ki6EigE',
    appId: '1:224201999490:web:1c87801d82d8a48e45a09b',
    messagingSenderId: '224201999490',
    projectId: 'khub-2d21b',
    authDomain: 'khub-2d21b.firebaseapp.com',
    storageBucket: 'khub-2d21b.firebasestorage.app',
    measurementId: 'G-ENKQWW1VDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijWbsYdgDmbrEANcwCIxmsSFC_mW6mrg',
    appId: '1:224201999490:android:61ba46c5e61d1eab45a09b',
    messagingSenderId: '224201999490',
    projectId: 'khub-2d21b',
    storageBucket: 'khub-2d21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjuEIpQWXBdKyxg8olgW42oH30ivEQbMs',
    appId: '1:224201999490:ios:ead1494161f3fba545a09b',
    messagingSenderId: '224201999490',
    projectId: 'khub-2d21b',
    storageBucket: 'khub-2d21b.firebasestorage.app',
    iosBundleId: 'com.example.khub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjuEIpQWXBdKyxg8olgW42oH30ivEQbMs',
    appId: '1:224201999490:ios:ead1494161f3fba545a09b',
    messagingSenderId: '224201999490',
    projectId: 'khub-2d21b',
    storageBucket: 'khub-2d21b.firebasestorage.app',
    iosBundleId: 'com.example.khub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu-fvmCsw-UyKSCATxbpGho21-Ki6EigE',
    appId: '1:224201999490:web:3a8aa1125ac4fc9945a09b',
    messagingSenderId: '224201999490',
    projectId: 'khub-2d21b',
    authDomain: 'khub-2d21b.firebaseapp.com',
    storageBucket: 'khub-2d21b.firebasestorage.app',
    measurementId: 'G-NB5SKNNX4C',
  );

}